# Generated by Django 4.1.2 on 2022-10-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='directions',
            new_name='preparation',
        ),
    ]
